# Generated by Django 2.2.1 on 2019-12-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('status', models.CharField(choices=[('AUC', 'Auction'), ('PUR', 'Purchased'), ('ING', 'In Progress')], default='ING', max_length=3)),
                ('type', models.CharField(choices=[('AC', 'Auction'), ('FL', 'Flea Market')], default='FL', max_length=2)),
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pimg', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('stocksold', models.IntegerField(default=0)),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='product registered')),
                ('endtime', models.DateField(default=django.utils.timezone.now, verbose_name='auction ended')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shoppinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('bidtime', models.DateField(default=django.utils.timezone.now, verbose_name='bid made')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
