# Generated by Django 2.2.1 on 2019-12-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='sellid',
        ),
    ]
