# Generated by Django 2.2.1 on 2019-12-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191206_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tradeplace',
            field=models.CharField(default='Seoul', max_length=30),
        ),
    ]
