# Generated by Django 2.2.1 on 2019-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_tradeplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stocksold',
        ),
    ]
