# Generated by Django 2.2.1 on 2019-12-09 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pubdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='review made'),
        ),
    ]
