# Generated by Django 3.0 on 2019-12-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_review_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
