# Generated by Django 3.0 on 2019-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191212_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
