# Generated by Django 3.0 on 2019-12-18 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191217_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='endtime',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='auction ended'),
        ),
    ]
